-- ============================================================
-- INVENTORY MANAGEMENT SYSTEM
-- ORACLE DATABASE SCHEMA
-- ============================================================

-- ============================================================
-- SUPPLIERS
-- ============================================================

CREATE TABLE suppliers (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    supplier_name VARCHAR2(100) NOT NULL,

    phone VARCHAR2(20) NOT NULL,

    email VARCHAR2(150) NOT NULL,

    address VARCHAR2(255) NOT NULL,

    CONSTRAINT pk_suppliers
        PRIMARY KEY (supplier_id),

    CONSTRAINT uq_supplier_email
        UNIQUE (email)
);


-- ============================================================
-- PRODUCTS
-- ============================================================

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    product_name VARCHAR2(150) NOT NULL,

    category VARCHAR2(100) NOT NULL,

    unit_price NUMBER(12,2)
        DEFAULT 0
        NOT NULL,

    quantity_in_stock NUMBER
        DEFAULT 0
        NOT NULL,

    reorder_level NUMBER
        DEFAULT 10
        NOT NULL,

    supplier_id NUMBER NOT NULL,

    CONSTRAINT pk_products
        PRIMARY KEY (product_id),

    CONSTRAINT fk_product_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id),

    CONSTRAINT chk_product_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_product_stock
        CHECK (quantity_in_stock >= 0),

    CONSTRAINT chk_product_reorder
        CHECK (reorder_level >= 0)
);


-- ============================================================
-- PURCHASE ORDERS
-- ============================================================

CREATE TABLE purchase_orders (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    supplier_id NUMBER NOT NULL,

    order_date DATE
        DEFAULT SYSDATE
        NOT NULL,

    status VARCHAR2(20)
        DEFAULT 'PENDING'
        NOT NULL,

    total_amount NUMBER(14,2)
        DEFAULT 0
        NOT NULL,

    CONSTRAINT pk_purchase_orders
        PRIMARY KEY (order_id),

    CONSTRAINT fk_order_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id),

    CONSTRAINT chk_order_status
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'RECEIVED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_order_total
        CHECK (total_amount >= 0)
);


-- ============================================================
-- ORDER ITEMS
-- ============================================================

CREATE TABLE order_items (
    order_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    order_id NUMBER NOT NULL,

    product_id NUMBER NOT NULL,

    quantity NUMBER NOT NULL,

    unit_price NUMBER(12,2) NOT NULL,

    subtotal NUMBER(14,2)
        DEFAULT 0
        NOT NULL,

    CONSTRAINT pk_order_items
        PRIMARY KEY (order_item_id),

    CONSTRAINT fk_item_order
        FOREIGN KEY (order_id)
        REFERENCES purchase_orders(order_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_item_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT uq_order_product
        UNIQUE (order_id, product_id),

    CONSTRAINT chk_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_item_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_item_subtotal
        CHECK (subtotal >= 0)
);


-- ============================================================
-- STOCK TRANSACTIONS
-- ============================================================

CREATE TABLE stock_transactions (
    transaction_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY,

    product_id NUMBER NOT NULL,

    transaction_type VARCHAR2(20) NOT NULL,

    quantity NUMBER NOT NULL,

    transaction_date TIMESTAMP
        DEFAULT SYSTIMESTAMP
        NOT NULL,

    reference VARCHAR2(100),

    remarks VARCHAR2(255),

    CONSTRAINT pk_stock_transactions
        PRIMARY KEY (transaction_id),

    CONSTRAINT fk_transaction_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT chk_transaction_type
        CHECK (
            transaction_type IN (
                'STOCK_IN',
                'STOCK_OUT',
                'ADJUSTMENT'
            )
        ),

    CONSTRAINT chk_transaction_quantity
        CHECK (quantity > 0)
);


-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_products_supplier
ON products(supplier_id);


CREATE INDEX idx_orders_supplier
ON purchase_orders(supplier_id);


CREATE INDEX idx_order_items_order
ON order_items(order_id);


CREATE INDEX idx_order_items_product
ON order_items(product_id);


CREATE INDEX idx_stock_product
ON stock_transactions(product_id);


COMMIT;

------------------------------------------------------------
-- INVENTORY MANAGEMENT SYSTEM
-- REQUIRED RELATIONSHIP QUERIES
------------------------------------------------------------


-- ==========================================================
-- QUERY 1
-- Products supplied by a particular supplier
-- ==========================================================

SELECT
    s.supplier_id,
    s.supplier_name,
    p.product_id,
    p.product_name,
    p.category,
    p.unit_price,
    p.quantity_in_stock,
    p.reorder_level
FROM suppliers s
JOIN products p
    ON s.supplier_id = p.supplier_id
WHERE s.supplier_id = 1
ORDER BY p.product_name;


-- ==========================================================
-- QUERY 2
-- Purchase orders belonging to a supplier
-- ==========================================================

SELECT
    s.supplier_id,
    s.supplier_name,
    po.order_id,
    po.order_date,
    po.status,
    po.total_amount
FROM suppliers s
JOIN purchase_orders po
    ON s.supplier_id = po.supplier_id
WHERE s.supplier_id = 1
ORDER BY po.order_date DESC;


-- ==========================================================
-- QUERY 3
-- Stock transactions for a particular product
-- ==========================================================

SELECT
    p.product_id,
    p.product_name,
    st.transaction_id,
    st.transaction_type,
    st.quantity,
    st.transaction_date,
    st.reference,
    st.remarks
FROM products p
JOIN stock_transactions st
    ON p.product_id = st.product_id
WHERE p.product_id = 1
ORDER BY st.transaction_date DESC;


-- ==========================================================
-- COMPLEX QUERY 4
-- Supplier + Purchase Order + Order Item + Product
-- ==========================================================

SELECT
    s.supplier_name,
    po.order_id,
    po.order_date,
    po.status,
    p.product_name,
    oi.quantity,
    oi.unit_price,
    oi.subtotal
FROM suppliers s
JOIN purchase_orders po
    ON s.supplier_id = po.supplier_id
JOIN order_items oi
    ON po.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
ORDER BY
    po.order_date DESC,
    s.supplier_name,
    p.product_name;


-- ==========================================================
-- COMPLEX QUERY 5
-- Product + Supplier + Stock Transactions
-- ==========================================================

SELECT
    p.product_id,
    p.product_name,
    s.supplier_name,
    st.transaction_type,
    st.quantity,
    st.transaction_date,
    st.reference,
    st.remarks
FROM products p
JOIN suppliers s
    ON p.supplier_id = s.supplier_id
JOIN stock_transactions st
    ON p.product_id = st.product_id
ORDER BY
    st.transaction_date DESC;